name: Workflow Keepalive
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
